FROM atlassian/bitbucket-server
MAINTAINER Tobias Oberrauch <tobias@uidriven.com>

USER root
VOLUME ["/data/bitbucket", "/var/atlassian/application-data/bitbucket"]
RUN chown -R daemon  /var/atlassian/application-data/bitbucket